# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\GameDev\MyLearning\PicReaper\base_qt.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(270, 480)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        Form.setMinimumSize(QtCore.QSize(270, 480))
        Form.setMaximumSize(QtCore.QSize(270, 480))
        self.bg_image = QtWidgets.QLabel(Form)
        self.bg_image.setGeometry(QtCore.QRect(0, 0, 270, 480))
        self.bg_image.setText("")
        self.bg_image.setPixmap(QtGui.QPixmap(":/BG/bg_fo4.png"))
        self.bg_image.setScaledContents(True)
        self.bg_image.setObjectName("bg_image")
        self.groupBox = QtWidgets.QGroupBox(Form)
        self.groupBox.setGeometry(QtCore.QRect(10, 330, 250, 128))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setStyleSheet("QLabel, QPushButton, QLineEdit{\n"
"    color: rgb(85, 170, 255);    \n"
"    background-color:rgba(0,0,0,0);\n"
"    font: 12pt \"MS Shell Dlg 2\";\n"
"    border: 1px solid rgb(85, 170, 255);}\n"
"QComboBox QAbstractItemView {\n"
"    color: rgb(85, 170, 255);\n"
"    background-color: qlineargradient(spread:reflect, x1:0.176273, y1:0.188, x2:0.602727, y2:0.659, stop:0 rgba(10, 11, 46, 216), stop:1 rgba(126, 118, 200, 185));\n"
"    selection-background-color: rgb(85, 85, 120);}\n"
"QComboBox {\n"
"    color: rgb(85, 170, 255);    \n"
"    padding-left: 10;\n"
"    border: 1px solid rgb(85, 170, 255);\n"
"    background-color:rgba(0,0,0,0)}\n"
"QComboBox::drop-down{\n"
"    image: url(:/UI/down-arrow.png);\n"
"    width: 24;\n"
"    height: 24;\n"
"    subcontrol-position: center right;\n"
"    margin-right: 4px;}\n"
"QGroupBox{\n"
"    background-color: qlineargradient(spread:reflect, x1:0.176273, y1:0.188, x2:0.602727, y2:0.659, stop:0 rgba(10, 11, 46, 216), stop:1 rgba(126, 118, 200, 185));\n"
"    border: 2px solid rgb(85, 170, 255);\n"
"    border-radius: 16;}")
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.label_game = QtWidgets.QLabel(self.groupBox)
        self.label_game.setGeometry(QtCore.QRect(0, 0, 90, 32))
        self.label_game.setStyleSheet("border-top-left-radius: 16;")
        self.label_game.setObjectName("label_game")
        self.box_game = QtWidgets.QComboBox(self.groupBox)
        self.box_game.setGeometry(QtCore.QRect(90, 0, 160, 32))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.box_game.setFont(font)
        self.box_game.setAutoFillBackground(False)
        self.box_game.setStyleSheet("border-top-right-radius: 16;")
        self.box_game.setObjectName("box_game")
        self.box_game.addItem("")
        self.box_game.addItem("")
        self.box_game.addItem("")
        self.label_category = QtWidgets.QLabel(self.groupBox)
        self.label_category.setGeometry(QtCore.QRect(0, 32, 90, 32))
        self.label_category.setStyleSheet("")
        self.label_category.setObjectName("label_category")
        self.box_category = QtWidgets.QComboBox(self.groupBox)
        self.box_category.setGeometry(QtCore.QRect(90, 32, 160, 32))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.box_category.setFont(font)
        self.box_category.setAutoFillBackground(False)
        self.box_category.setStyleSheet("")
        self.box_category.setObjectName("box_category")
        self.box_category.addItem("")
        self.box_category.addItem("")
        self.box_category.addItem("")
        self.label_directory = QtWidgets.QLabel(self.groupBox)
        self.label_directory.setGeometry(QtCore.QRect(0, 64, 90, 32))
        self.label_directory.setStyleSheet("")
        self.label_directory.setObjectName("label_directory")
        self.btn_browsedir = QtWidgets.QPushButton(self.groupBox)
        self.btn_browsedir.setGeometry(QtCore.QRect(90, 64, 160, 32))
        self.btn_browsedir.setStyleSheet("padding-right: 16;\n"
"text-align:right;")
        self.btn_browsedir.setObjectName("btn_browsedir")
        self.label_startpage = QtWidgets.QLabel(self.groupBox)
        self.label_startpage.setGeometry(QtCore.QRect(0, 96, 80, 32))
        self.label_startpage.setStyleSheet("border-bottom-left-radius: 16;")
        self.label_startpage.setObjectName("label_startpage")
        self.edit_startpage = QtWidgets.QLineEdit(self.groupBox)
        self.edit_startpage.setGeometry(QtCore.QRect(80, 96, 45, 32))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.edit_startpage.setFont(font)
        self.edit_startpage.setStyleSheet("")
        self.edit_startpage.setMaxLength(4)
        self.edit_startpage.setAlignment(QtCore.Qt.AlignCenter)
        self.edit_startpage.setObjectName("edit_startpage")
        self.label_endpage = QtWidgets.QLabel(self.groupBox)
        self.label_endpage.setGeometry(QtCore.QRect(125, 96, 80, 32))
        self.label_endpage.setStyleSheet("")
        self.label_endpage.setObjectName("label_endpage")
        self.edit_endpage = QtWidgets.QLineEdit(self.groupBox)
        self.edit_endpage.setGeometry(QtCore.QRect(205, 96, 45, 32))
        self.edit_endpage.setStyleSheet("border-bottom-right-radius:16;")
        self.edit_endpage.setMaxLength(4)
        self.edit_endpage.setAlignment(QtCore.Qt.AlignCenter)
        self.edit_endpage.setObjectName("edit_endpage")
        self.btn_start_parse = QtWidgets.QPushButton(Form)
        self.btn_start_parse.setEnabled(True)
        self.btn_start_parse.setGeometry(QtCore.QRect(40, 285, 190, 36))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_start_parse.sizePolicy().hasHeightForWidth())
        self.btn_start_parse.setSizePolicy(sizePolicy)
        self.btn_start_parse.setMinimumSize(QtCore.QSize(190, 36))
        self.btn_start_parse.setMaximumSize(QtCore.QSize(190, 36))
        self.btn_start_parse.setStyleSheet("background-color: qlineargradient(spread:reflect, x1:0.176273, y1:0.188, x2:0.602727, y2:0.659, stop:0 rgb(10, 11, 46), stop:1 rgb(126, 118, 200));\n"
"border: 2px solid rgb(85, 170, 255);\n"
"border-radius: 16;\n"
"color: rgb(85, 170, 255);    \n"
"font: 12pt \"MS Shell Dlg 2\";")
        self.btn_start_parse.setObjectName("btn_start_parse")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "PicReaper"))
        self.label_game.setText(_translate("Form", "GAME"))
        self.box_game.setItemText(0, _translate("Form", "Fallout 4"))
        self.box_game.setItemText(1, _translate("Form", "Skyrim SE"))
        self.box_game.setItemText(2, _translate("Form", "Skyrim"))
        self.label_category.setText(_translate("Form", "Category"))
        self.box_category.setItemText(0, _translate("Form", "Aesthetic"))
        self.box_category.setItemText(1, _translate("Form", "Combat"))
        self.box_category.setItemText(2, _translate("Form", "Funny"))
        self.label_directory.setText(_translate("Form", "Directory"))
        self.btn_browsedir.setText(_translate("Form", "..."))
        self.label_startpage.setText(_translate("Form", "Start Page"))
        self.edit_startpage.setText(_translate("Form", "1"))
        self.label_endpage.setText(_translate("Form", "End Page"))
        self.edit_endpage.setText(_translate("Form", "1"))
        self.btn_start_parse.setText(_translate("Form", "! START !"))
import gui_rc
